
package tabletennis;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.sql.*;

public class LogOnGUI extends javax.swing.JFrame {
    
    public static String username;

    /**
     * Creates new form LogOnGUI
     */
    public LogOnGUI() {
        initComponents();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbType = new javax.swing.JComboBox<>();
        btnWeather = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblLogOn = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        pwfPassword = new javax.swing.JPasswordField();
        btnLogOn = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Table Tennis Log On");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbType.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Participant" }));
        getContentPane().add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        btnWeather.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        btnWeather.setText("Weather");
        btnWeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeatherActionPerformed(evt);
            }
        });
        getContentPane().add(btnWeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 120, -1));

        lblUsername.setBackground(new java.awt.Color(204, 204, 204));
        lblUsername.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        lblLogOn.setBackground(new java.awt.Color(204, 204, 204));
        lblLogOn.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblLogOn.setText("Log on as");
        getContentPane().add(lblLogOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        lblPassword.setBackground(new java.awt.Color(204, 204, 204));
        lblPassword.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 140, -1));
        getContentPane().add(pwfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 140, -1));

        btnLogOn.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        btnLogOn.setText("Log On");
        btnLogOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOnActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabletennis/TT1.jpg"))); // NOI18N
        lblBackground.setText("jLabel2");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1120, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void btnLogOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOnActionPerformed
        // TODO add your handling code here:
        
        //Get input which user typed or selected
        String type = cmbType.getSelectedItem().toString();
        String un = txfUsername.getText();
        String pw = pwfPassword.getText();
        
        //check user typed at least one character in username or password
        if(un.length() == 0 | pw.length() == 0){
            //display error
            lblLogOn.setText("Please enter usename and/or password");
        }else{
        //check username and password according to type
        if(type.equalsIgnoreCase("Administrator"))
             checkAdministrator(un,pw);
        else
            //display error message
            System.out.println("File not found.");
        
        if(type.equalsIgnoreCase("Participant")){
            checkParticipant(un, pw);
            
            //save user name as static field called username;
            username = un;
        }
        }
    }//GEN-LAST:event_btnLogOnActionPerformed

    private void btnWeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeatherActionPerformed
        // TODO add your handling code here:
        
        new Weather().setVisible(true);
                    
        //make Log on form invisible 
        this.dispose();
    }//GEN-LAST:event_btnWeatherActionPerformed
    
    //method for check administrator's password and username
    void checkAdministrator(String un, String pw){
        try{
            //scan file adminPassword.txt
            Scanner inFile = new Scanner(new FileReader ("AdminPassword.txt"));
            
            String line, AdName, AdSurname, AdUsername, AdPassword;
            int AdID;
            
            /*Extract line, adName, adSurname, AdUsername and 
            AdPassword from text file*/
            while(inFile.hasNext()){
                line = inFile.nextLine();
                Scanner sc = new Scanner(line).useDelimiter("#");
                AdID = sc.nextInt();
                AdName = sc.next();
                AdSurname = sc.next();
                AdUsername = sc.next();
                AdPassword = sc.next();
                
                
                /*check username and password which user typed are in the 
                text file and username is matched to password*/
                if(AdUsername.equalsIgnoreCase(un) && 
                    AdPassword.equalsIgnoreCase(pw)){
                    
                    //display form for administrator 
                    new MainGUI().setVisible(true);
                    
                    //make Log on form invisible 
                    this.dispose();
                    
                }else {
                    //display error message
                    lblLogOn.setText("Incorrect name or password");
                }
                
            }
        }catch (FileNotFoundException ex){
            //display error message
            lblLogOn.setText("File Not Found");
        }
    }
    
    //method for check participant's password and username
    void checkParticipant(String un, String pw){
        try{
            //extract data from database called tblParticipant
            ResultSet rs = CompetitionManager.db.queryDB
            ("SELECT * FROM tblParticipant WHERE PpUsername = '" + un + "';");
            
            //Declare and initiate variable
            String password ="";
            
            /*save PpPassword field in database 
            called tblParticipant as password*/
           while(rs.next()){password = rs.getString("PpPassword");}
           
           //check password equals to the password which user typed
            if(password.equalsIgnoreCase(pw) ){
                //save username as static field called username
                username = un;
                
                //display form for participant
                new ParticipantsGUI().setVisible(true);
                
                //make Log On form invisible 
                this.dispose();
                
            }else{
                //display error message
                lblLogOn.setText("Incorrect name or password");
            }
        }catch(SQLException ex){
            
            //display error message
            lblLogOn.setText("Cannot access Participant table");
        }
        
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOnGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOn;
    private javax.swing.JButton btnWeather;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogOn;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
