
package tabletennis;

import java.sql.ResultSet;
import java.sql.SQLException;

public class ParticipantsGUI extends javax.swing.JFrame {
    
    CompetitionManager cm;
    
    /**
     * Creates new form ParticipantsGUI
     */
    public ParticipantsGUI() {
        initComponents();
        
        try{
            //Declare competition manager object
            cm = new CompetitionManager();
        }catch(SQLException ex){
            //Display error message
            lblViewCompetitionsError.setText("Cannot load Competitions");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlViewCompetitions = new javax.swing.JPanel();
        btnShowAllCompetitions = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaViewCompetitions = new javax.swing.JTextArea();
        lblViewCompetitionsError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlViewResults = new javax.swing.JPanel();
        btnShowAllResults = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaViewResults = new javax.swing.JTextArea();
        lblBackground10 = new javax.swing.JLabel();
        lblViewResultsError = new javax.swing.JLabel();
        pnlHelp = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        btnViewCompetitions = new javax.swing.JButton();
        btnViewResults = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaHelp = new javax.swing.JTextArea();
        lblBackground11 = new javax.swing.JLabel();
        lblHelpError = new javax.swing.JLabel();
        pnlLogOut = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnlViewCompetitions.setLayout(null);

        btnShowAllCompetitions.setText("Show All Competitions");
        btnShowAllCompetitions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllCompetitionsActionPerformed(evt);
            }
        });
        pnlViewCompetitions.add(btnShowAllCompetitions);
        btnShowAllCompetitions.setBounds(474, 61, 151, 23);

        txaViewCompetitions.setColumns(20);
        txaViewCompetitions.setRows(5);
        jScrollPane1.setViewportView(txaViewCompetitions);

        pnlViewCompetitions.add(jScrollPane1);
        jScrollPane1.setBounds(44, 125, 1006, 370);

        lblViewCompetitionsError.setForeground(new java.awt.Color(255, 51, 51));
        lblViewCompetitionsError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabletennis/TT3.jpg"))); // NOI18N
        lblViewCompetitionsError.setText("jLabel1");
        pnlViewCompetitions.add(lblViewCompetitionsError);
        lblViewCompetitionsError.setBounds(-3, -4, 1110, 630);

        jLabel1.setText("jLabel1");
        pnlViewCompetitions.add(jLabel1);
        jLabel1.setBounds(490, 550, 38, 16);

        jTabbedPane1.addTab("View Competitions", pnlViewCompetitions);

        pnlViewResults.setLayout(null);

        btnShowAllResults.setText("Show All Results");
        btnShowAllResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllResultsActionPerformed(evt);
            }
        });
        pnlViewResults.add(btnShowAllResults);
        btnShowAllResults.setBounds(490, 61, 116, 23);

        txaViewResults.setColumns(20);
        txaViewResults.setRows(5);
        jScrollPane2.setViewportView(txaViewResults);

        pnlViewResults.add(jScrollPane2);
        jScrollPane2.setBounds(49, 129, 994, 423);

        lblBackground10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabletennis/TT3.jpg"))); // NOI18N
        lblBackground10.setText("jLabel2");
        pnlViewResults.add(lblBackground10);
        lblBackground10.setBounds(-3, -4, 1110, 630);

        lblViewResultsError.setText("jLabel2");
        pnlViewResults.add(lblViewResultsError);
        lblViewResultsError.setBounds(530, 580, 38, 16);

        jTabbedPane1.addTab("View results", pnlViewResults);

        pnlHelp.setLayout(null);

        lblHelp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(255, 255, 255));
        lblHelp.setText("Click on the button to see help on a particular topic:");
        pnlHelp.add(lblHelp);
        lblHelp.setBounds(91, 58, 493, 25);

        btnViewCompetitions.setText("View Competitions");
        btnViewCompetitions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCompetitionsActionPerformed(evt);
            }
        });
        pnlHelp.add(btnViewCompetitions);
        btnViewCompetitions.setBounds(91, 182, 130, 23);

        btnViewResults.setText("View Results");
        btnViewResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResultsActionPerformed(evt);
            }
        });
        pnlHelp.add(btnViewResults);
        btnViewResults.setBounds(91, 276, 130, 23);

        txaHelp.setColumns(20);
        txaHelp.setRows(5);
        jScrollPane3.setViewportView(txaHelp);

        pnlHelp.add(jScrollPane3);
        jScrollPane3.setBounds(303, 129, 439, 237);

        lblBackground11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabletennis/TT1.jpg"))); // NOI18N
        lblBackground11.setText("jLabel3");
        pnlHelp.add(lblBackground11);
        lblBackground11.setBounds(-3, -4, 1110, 630);
        pnlHelp.add(lblHelpError);
        lblHelpError.setBounds(790, 150, 0, 0);

        jTabbedPane1.addTab("Help", pnlHelp);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogOutLayout = new javax.swing.GroupLayout(pnlLogOut);
        pnlLogOut.setLayout(pnlLogOutLayout);
        pnlLogOutLayout.setHorizontalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        pnlLogOutLayout.setVerticalGroup(
            pnlLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Log Out", pnlLogOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllCompetitionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllCompetitionsActionPerformed
        // TODO add your handling code here:
        //Decalre competition array
        Competition competition[] = new Competition[1000];
        
        //Declare and initialise variables
        int size = 1;
        String t, l;
        int cID , p;
        String d;
        
        try{
        //Extract data from database
        ResultSet rs = CompetitionManager.db.queryDB("SELECT * FROM tblCompetition;");
        
        while(rs.next()){
            
            cID = Integer.parseInt(rs.getString("CpID"));
            t = rs.getString("CpTitle");
            l = rs.getString("CpLocation");
            p = Integer.parseInt(rs.getString("CpPrize"));
            d = (rs.getString("CpDate")).substring(0,10);
            
           //Add new object to the array
            competition[size] = new Competition(cID, t, l, p, d);
            size++;
        }
        
        String temp = "";
        
        //Add column name to the first line
        temp+= "ID" + addSpaces("ID",10) +
                "Title" + addSpaces("Title",35) + 
                "Location" + addSpaces("Location",25) +
                "Prize" + addSpaces("Prize", 10)+
                "Date";
        temp += "\n";
        
        
        for(int i = 0; i < size; i++){
            //Add details of each competition to the next line
            if(competition[i] != null){
                temp += competition[i].getCpID() + addSpaces(String.valueOf(competition[i].getCpID()), 10);
                temp += competition[i].getCpTitle() + addSpaces(competition[i].getCpTitle(), 35);
                temp += competition[i].getCpLocation() + addSpaces(String.valueOf(competition[i].getCpLocation()), 25);
                temp += competition[i].getCpPrize() + addSpaces(String.valueOf(competition[i].getCpPrize()), 10);
                temp += competition[i].getCpDate();
            }
            temp += "\n";
        
        }
            //Display competition detail
            txaViewCompetitions.setText(temp);
            
        }catch(SQLException ex){
            //Display an error message
            lblViewCompetitionsError.setText("Cannot load the data");
        }
        
    }//GEN-LAST:event_btnShowAllCompetitionsActionPerformed

    private void btnShowAllResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllResultsActionPerformed
        // TODO add your handling code here:
        //Specify user
        String user = LogOnGUI.username;
        
        try{
            //Add column name to the first line of output
            String temp = "";
            temp += "Competition ID" + addSpaces("Competition ID" , 20);
            temp += "Competition" + addSpaces("Competition" , 20);
            temp += "Points" + "\n" + "\n";
            
            //Extract data from database
            ResultSet rs = CompetitionManager.db.queryDB("SELECT  CpID, CpTitle, TotalPoints FROM tblResult, tblParticipant, tblCompetition  WHERE tblResult.PpID = tblParticipant.PpID AND tblCompetition.CpID = tblResult.CpID AND tblParticipant.PpUsername = " + " '" + user + "' " + "ORDER BY tblResult.Totalpoints");
            
            while(rs.next()){
                //Add results of each competition to the next line
                temp += rs.getString("CpID") + addSpaces(rs.getString("CpID"),20);
                temp += rs.getString("CpTitle") + addSpaces(rs.getString("CpTitle"), 20);
                temp += rs.getString("TotalPoints") + "\n";
            }
            //Display result details
            txaViewResults.setText(temp);
        }catch(SQLException es){
            //Display error message
            lblViewResultsError.setText("Cannot load results");
        }
    }//GEN-LAST:event_btnShowAllResultsActionPerformed

    private void btnViewCompetitionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCompetitionsActionPerformed
        // TODO add your handling code here:
        //Get the topic chosen by user
        String topic = evt.getActionCommand();
        try{
            
        //Extract data from database
        ResultSet rs = CompetitionManager.db.queryDB("SELECT Description FROM tblHelp WHERE Problem = " + " '" + topic + "';");
        rs.next();
        String d = rs.getString("Description");
        
        //Display description
        txaHelp.setText(d);
        }catch(SQLException ex){
            
         //Display error message
         lblHelpError.setText("Cannot access Help");
        }
    }//GEN-LAST:event_btnViewCompetitionsActionPerformed

    private void btnViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResultsActionPerformed
        // TODO add your handling code here:
        //Get the topic chosen by user 
        String topic = evt.getActionCommand();
        try{
            
        //Extract data from database    
        ResultSet rs = CompetitionManager.db.queryDB("SELECT Description FROM tblHelp WHERE Problem = " + " '" + topic + "';");
        rs.next();
        String d = rs.getString("Description");
        
        //Display description
        txaHelp.setText(d);
        }catch(SQLException ex){
            
         //Display error message
         lblHelpError.setText("Cannot access Help");
        }
    }//GEN-LAST:event_btnViewResultsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        //Display new Log On interface
        new LogOnGUI().setVisible(true);
        //Set Main interface invisible
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipantsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipantsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipantsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipantsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipantsGUI().setVisible(true);
            }
        });
    }
    
    private static String addSpaces(String s, int width)
    {
        //Declare and initialise variable
        String newString = "";
        
        //Add spaces till the String and spaces are as long as "width"
        for(int i = 0; i< width - s.length();i++)
        {
            //Add a space
            newString +=" ";
        }
        //if the value is Double, take away the size of space that '.' has
        
        //return the spaces as a 'newString'
        return newString;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnShowAllCompetitions;
    private javax.swing.JButton btnShowAllResults;
    private javax.swing.JButton btnViewCompetitions;
    private javax.swing.JButton btnViewResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBackground10;
    private javax.swing.JLabel lblBackground11;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblHelpError;
    private javax.swing.JLabel lblViewCompetitionsError;
    private javax.swing.JLabel lblViewResultsError;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlLogOut;
    private javax.swing.JPanel pnlViewCompetitions;
    private javax.swing.JPanel pnlViewResults;
    private javax.swing.JTextArea txaHelp;
    private javax.swing.JTextArea txaViewCompetitions;
    private javax.swing.JTextArea txaViewResults;
    // End of variables declaration//GEN-END:variables
}
